name: Draft Release

on:
  push:
    branches: [main]

jobs:
  estimate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Timestamp
        run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV
      - name: write foo
        uses: softprops/action-gh-release@v2
        with:
          tag_name: dino/foo/${{ env.TIMESTAMP }}
          draft: true
          generate_release_notes: true